### ISSUE TITLE
feat: integrate GitHub status API

### ISSUE THREAD

**Issue by wsameer** [wsameer/octoprofile-plus#17]
In this feature request, we would like to show the status of GitHub.

The status could be seen in the right corner of the header below the rate limit count.
![image](https://user-images.githubusercontent.com/8468992/135741254-7681f6d8-30ff-4bd9-bb15-2302cd5cbde3.png)
In case of error, use "❌" this emoji.

This [GitHub Status API](https://www.githubstatus.com/api/v2/status.json) is the API that you would be calling to get the status.
This API should be called only once, when the web app is started.

If you've any questions, you can write them down in the comments, or ping me on twitter [@SameerWaskar](https://twitter.com/SameerWaskar)

**Comment by Agreon** [comment]
I'd like to try that :)

**Comment by wsameer** [comment]
@Agreon  all yours :) Please do leave a start on the repo and spread the word.
