### ISSUE TITLE
fix: make the sidebar's position fix

### ISSUE THREAD

**Issue by wsameer** [wsameer/octoprofile-plus#18]
Currently the sidebar's height depends on the height of the content of the page.
We would like the Sidebar to occupy a full page height all the time with "Support" link visible at the bottom.

![image](https://user-images.githubusercontent.com/8468992/135741546-902165af-bf28-46e3-ab3b-f203f5df9f2e.png)

Note, that if the data in the tab content section scrolls, the Sidebar should not move.

**Comment by 1337-ishaan** [comment]
Pls assign

**Comment by 1337-ishaan** [comment]
@wsameer #19

**Comment by wsameer** [comment]
@1337-ishaan  all yours :) Please do leave a start on the repo and spread the word.

**Comment by 1337-ishaan** [comment]
Fixed this #19

**Comment by 1337-ishaan** [comment]
Completed! Pls check #22
